<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorvotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorvotesRepository extends EntityRepository
{
    public function findbyauthorandip($id, $iphash)
    {
        $qb = $this->createQueryBuilder('a')
                ->where('a.authorid = :id')
                ->andWhere('a.iphash = :iphash')
                ->setParameter('id', $id)
                ->setParameter('iphash', $iphash);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
