<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;


/**
 * ChillingdmcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChillingdmcaRepository extends EntityRepository
{
    public function findAllPaged()
    {
        $qb = $this->createQueryBuilder('c');
        $adapter = new DoctrineORMAdapter($qb);
        return new Pagerfanta($adapter);
    }
}
