<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DailydownloadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailydownloadsRepository extends EntityRepository
{
    function getTotalDownloadCount()
    {
        return $this->getEntityManager()->getConnection()
                ->executeQuery('select sum(downloads) from dailydownloads')
                ->fetch(\Doctrine\ORM\Query::HYDRATE_SINGLE_SCALAR);
    }
}
