<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends EntityRepository
{
    public function totaldownloadcount()
    {
        $qb = $this->createQueryBuilder('d')
                ->select('count(d.id)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
