<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends EntityRepository
{
    public function totaldownloadcount()
    {
        $qb = $this->createQueryBuilder('d')
                ->select('count(d.id)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function findByBookandIphash($book, $iphash)
    {
        $qb = $this->createQueryBuilder('d')
                ->where('d.book = :book')
                ->andWhere('d.ip = :iphash')
                ->setParameter('book', $book)
                ->setParameter('iphash', $iphash);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
