<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{
    public function findByBookandIpHash($book, $iphash)
    {
        $qb = $this->createQueryBuilder('r')
                ->where('r.bookid = :book')
                ->andWhere('r.iphash = :iphash')
                ->setParameter('book', $book)
                ->setParameter('iphash', $iphash);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function findByBook($book)
    {
        $qb = $this->createQueryBuilder('r')
                ->where('r.bookid = :book')
                ->setParameter('book', $book);
        
        return $qb->getQuery()->execute();
    }
    
    public function totalratingcount()
    {
        $qb = $this->createQueryBuilder('r')
                ->select('count(r.id)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
