<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * TaggingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaggingRepository extends EntityRepository
{
    public function findResourcesByTypeandTag($type, $tag)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.resourceType = :type')
            ->andWhere('t.tag = :tag')
            ->setParameter('type', $type)
            ->setParameter('tag', $tag);
        
        $adapter = new DoctrineORMAdapter($qb);
        return new Pagerfanta($adapter);
    }
    public function findResourcesByTag($tag)
    {
        $qb = $this->createQueryBuilder('t')
            ->Where('t.tag = :tag')
            ->setParameter('tag', $tag);
        
        return $qb->getQuery()->execute();
    }
}
