<?php

namespace matuck\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;


/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * 
     * @return \Pagerfanta\Pagerfanta
     */
    public function populartags()
    {
        $qb = $this->createQueryBuilder('t')
                ->select('t, COUNT(t2.id) AS tagcount')
                ->leftJoin('t.tagging', 't2')
                ->groupBy('t.id')
                ->having('tagcount > 0')
                ->orderBy('tagcount', 'desc');
        $adapter = new DoctrineORMAdapter($qb);
        return new Pagerfanta($adapter);
    }
    
    public function findAllPagerOrderbyName()
    {
        $qb = $this->createQueryBuilder('t')
                ->orderBy('t.name', 'ASC');
        $adapter = new DoctrineORMAdapter($qb);
        
        return new Pagerfanta($adapter);
    }
    
    public function findByBookswithNumber()
    {
        $qb = $this->createQueryBuilder('t')
                ->orderBy('t.name', 'ASC');
        $qb->andWhere($qb->expr()->like('t.name', $qb->expr()->literal('0%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('1%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('2%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('3%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('4%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('5%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('6%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('7%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('8%')).' OR '.$qb->expr()->like('t.name', $qb->expr()->literal('9%')));
        $adapter = new DoctrineORMAdapter($qb);
        
        return new Pagerfanta($adapter);
    }
    
    public function findByFirstLetterPaged($letter)
    {
        $qb = $this->createQueryBuilder('t')
                ->andWhere('t.name LIKE :letter')
                ->orderBy('t.name', 'ASC')
                ->setParameter('letter', $letter.'%');
        
        $adapter = new DoctrineORMAdapter($qb);
        
        return new Pagerfanta($adapter);
    }
}
